web:
  image: nginx:latest
  ports:
    - "127.0.0.1:80:80"
  volumes:
    - ./deraner:/var/www/deraner
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - app

app:
  build: ./app
  volumes:
    - ./deraner:/var/www/deraner
    - ./app/php-fpm.conf:/usr/local/etc/php-fpm.d/deraner.conf
    - ./app/.zshrc:/root/.zshrc
  links:
    - mysql
    - redis

mysql:
  image: mariadb:latest
  ports:
    - "127.0.0.1:3316:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=deraner
  volumes:
   - ./tmp:/var/lib/mysql

redis:
  image: redis:latest