security:
  providers:
    db_provider:
      entity:
        class: Deraner\Entity\User
        property: mail
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: ~
      form_login:
        login_path: security_login
        check_path: security_login
        default_target_path: security_success
  encoders:
    Deraner\Security\User:
      algorithm: bcrypt